name: docker-compose-actions-workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -it
      - name: Test
        run: npx wdio run conf/docker.conf.js --spec logining.module.js