name: main GitHubActions
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - name: Install webdriver
      run: npm install
    - name: Install service Standalone
      run: npm install @wdio/selenium-standalone-service --save-dev
    - name: Install Allure
      run: npm install allure-commandline --save-dev
    - name: run all test (Chrome, Firefox)
      run: npm run crossbrowser:test:headless
    - name: Copy History
      if: always()
      run: cp -r $(pwd)/docs/history/. $(pwd)/allure-results/history
    - name: Generate Report
      if: always()
      run: npm run allure-generate # Name of the allure generate script
    - name: Upload Results
      uses: actions/upload-artifact@v1
      if: always()
      with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results                    
    - name: Publishing Allure artifact to Github Actions
       
      uses: actions/upload-artifact@v2
      if: always()
      with:
          name: allure-report
          path: allure-report        
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: always()
      with:
          branch: main # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.
          target-folder: docs

