name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 16.x
        - name: Install
          run: npm install
        - name: Install Servic Standalon
          run: npm install @wdio/selenium-standalone-service --save-dev
        - name: Test
          run: npm run firefox:ui:messaging 
       
