name: main GitHubActions
on:
  push:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - name: Install webdriver
      run: npm install
    - name: Install service Standalone
      run: npm install @wdio/selenium-standalone-service --save-dev
    - name: Install Allure
      run: npm install allure-commandline --save-dev
    - name: run all test (Chrome, Firefox)
      run: npm run firefox:ui:messaging
    - name: Generate report
      if: always()
      run: npx allure generate allure-results --clean
    - name: Deploy to pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3.7.3
      with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-report

