name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
        - uses: actions/setup-node@v1
          with:
            node-version: 1
        - name: Install
          run: npm install
        - name: Install Selenium
          run: npm install @wdio/selenium-standalone-service --save-dev
        - name: Test
          run: npm run chrome:ui
        - uses: actions/upload-artifact@v1
          if: failure()
          with:
            name: logs
            path: logs
